### ISSUE TITLE
performance problems with get_bit

### ISSUE THREAD

**Issue by KonradHoeffner** [sujayakar/rsdict#4]
Running the custom get_bit function below many times with `cargo run --release` (including optimizations) takes 184ms, while using `self.dict.get_bit(word_index as u64)` instead takes 3.773s.  dict was created as `let dict = RsDict::from_blocks((data.clone() as Vec<u64>).into_iter());`.

Did I make a mistake somewhere or is it normal that there is so much of a discrepancy in runtime?

```Rust
const USIZE_BITS: usize = usize::BITS as usize;

#[derive(Debug, Clone)]
pub struct Bitmap {
    num_bits: usize,
    pub dict: RsDict,
    pub data: Vec<u64>,
}

impl BitMap {
 pub fn get_bit(&self, word_index: usize) -> bool {
        let block_index = word_index / USIZE_BITS;
        let bit_index = word_index % USIZE_BITS;
        let bit_flag = 1_u64 << bit_index;
        self.data[block_index] & bit_flag == bit_flag
    }
}
```

**Comment by sujayakar** [comment]
Hi @KonradHoeffner! This isn't actually that surprising to me, since it's storing the underlying bitmap in compressed form, only decoding blocks as they're needed for the `rank` and `select` computations. This ends up working well for those algorithms but I can see how it'd be slow for random bit access.

Is it acceptable for your use case to incur the extra memory of storing both `RsDict` and your bitset? The [original paper](https://users.dcc.uchile.cl/~gnavarro/ps/sea12.1.pdf) also has a version of the data structure that skips compression and just uses a regular bitset underneath its rank and select acceleration structures: I can try implementating that otherwise. I also haven't tried optimizing `get_bit` at all either... :)

**Comment by KonradHoeffner** [comment]
Oh hi, thanks for the quick reply and the clarification! Using both is fine for now, I just thought I did something wrong as I didn't know it is compressed.
I'm in the middle of a big refactoring and may well use much less get_bit operations at the end of it, at which point I need to remeasure everything, so I don't want to burden you with extra implementation work but thanks for the offer!
